# Generated by Django 4.2.4 on 2023-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="movie_videos"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                choices=[("all", "All"), ("kids", "Kids")], max_length=10
            ),
        ),
    ]
